services:
  scylladb:
    image: scylladb/scylla:5.4
    container_name: study-tool-scylladb
    ports:
      - "9042:9042"  # CQL port
      - "9160:9160"  # Thrift port
      - "10000:10000" # REST API port
    environment:
      - SCYLLA_CLUSTER_NAME=StudyToolCluster
      - SCYLLA_DC=datacenter1
      - SCYLLA_RACK=rack1
      - SCYLLA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - scylla_data:/var/lib/scylla
      - ./database/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - study-tool-network
    command: --seeds=scylladb --smp=1 --memory=2G --overprovisioned=1 --api-address=0.0.0.0
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "SELECT now() FROM system.local"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: study-tool-backend
    ports:
      - "8080:8080"
    environment:
      # Database configuration
      - DB_HOST=scylladb
      - DB_PORT=9042
      - DB_DATACENTER=datacenter1
      - DB_KEYSPACE=${DB_KEYSPACE:-studytool}
      - DB_USERNAME=${DB_USERNAME:-}
      - DB_PASSWORD=${DB_PASSWORD:-}
      
      # File storage configuration
      - FILE_STORAGE_PATH=/app/uploads
      
      # Vertex AI configuration
      - VERTEX_PROJECT_ID=${VERTEX_PROJECT_ID:-csi3370-study-tool}
      - VERTEX_LOCATION=${VERTEX_LOCATION:-us-central1}
      - VERTEX_TEXT_MODEL=${VERTEX_TEXT_MODEL:-gemini-2.0-flash-lite-001}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS:-/app/vertex-ai-key.json}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT:-${VERTEX_PROJECT_ID}}
      
      # Legacy environment variables (for backward compatibility)
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
    volumes:
      - ./uploads:/app/uploads
      # Mount the service account key file if it exists locally
      - ${VERTEX_AI_KEY_PATH:-./vertex-ai-key.json}:/app/vertex-ai-key.json:ro
    networks:
      - study-tool-network
    depends_on:
      scylladb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/hello"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: study-tool-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - study-tool-network
    environment:
      - REACT_APP_API_URL=http://localhost:8080

  scylla-init:
    image: scylladb/scylla:5.4
    depends_on:
      scylladb:
        condition: service_healthy
    volumes:
      - ./database/init-scripts:/init-scripts
    entrypoint:
      - /bin/sh
      - -c
      - >
        for f in /init-scripts/*.cql; do
          cqlsh scylladb 9042 -f "$$f";
        done
    networks:
      - study-tool-network

networks:
  study-tool-network:
    driver: bridge

volumes:
  scylla_data:
    driver: local

# Optional: Add database service when ready
# volumes:
#   postgres_data: 